version: '3'
services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gestao_api
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=banco123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DATABASES=db
      - POSTGRES_PASSWORD=banco123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gestao_api
      

version: '3'
services:
  pucsigo:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: pucsigo
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gestao_api
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=banco123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DATABASES=db
      - POSTGRES_PASSWORD=banco123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gestao_api